apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-backend
  template:
    metadata:
      labels:
        app: llm-backend
    spec:
      containers:
      - name: llm-backend
        image: llm-backend:latest
        imagePullPolicy: Never  
        ports:
        - containerPort: 5000
        env:
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: llm-api-keys
              key: GOOGLE_API_KEY
              optional: true
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: llm-api-keys
              key: OPENAI_API_KEY
              optional: true
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: llm-api-keys
              key: ANTHROPIC_API_KEY
              optional: true
        - name: XAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: llm-api-keys
              key: XAI_API_KEY
              optional: true
        - name: GLAMA_API_KEY
          valueFrom:
            secretKeyRef:
              name: llm-api-keys
              key: GLAMA_API_KEY
              optional: true
---
apiVersion: v1
kind: Service
metadata:
  name: llm-backend-service
spec:
  selector:
    app: llm-backend
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30855  # Choose a free port between 30000-32767
    protocol: TCP
  type: NodePort
