apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-backend
  template:
    metadata:
      labels:
        app: llm-backend
    spec:
      containers:
      - name: llm-backend
        image: llm-backend:latest
        imagePullPolicy: Never  
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: llm-backend-service
spec:
  selector:
    app: llm-backend
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30855  # Choose a free port between 30000-32767
    protocol: TCP
  type: NodePort
